//create user
###
POST http://localhost:5000/users/create
Content-Type: application/json

{
    "firstName":"alex",
    "lastName":"waihenya",
    "email":"lxwaihenya@gmail.com",
    "password":"12345678"
}
//LOGIN TO ACCOUNT
###
POST http://localhost:5000/users/login
Content-Type: application/json

{
    "email":"lxwaihenya@gmail.com",
    "password":"12345678"  
}

//CHECKUSER
###
GET http://localhost:5000/projects/check
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImZpcnN0TmFtZSI6ImFsZXgiLCJsYXN0TmFtZSI6IndhaWhlbnlhIiwiZW1haWwiOiJseHdhaWhlbnlhQGdtYWlsLmNvbSIsInJvbGUiOiIwIiwiaWF0IjoxNjYwNTEwNjk5LCJleHAiOjE2NjA1MTA5OTl9.wMgODeHNpaNX0IYHmtxQR-pnp-ZaVyJndgh97BtTaus


###
//CREATING A PROJECT
POST http://localhost:5000/projects/create
Content-Type: application/json

{
    "projectName":"abcd",
    "description":"hacking",
    "endDate":"12/3/2022"
}


//DELETING A PROJECT/
###
POST http://localhost:5000/projects/delete
Content-Type: application/json

{
    "projectId":"1"
}



// SET PROJECT AS COMPLETED/
###
POST http://localhost:5000/users/setDone
Content-Type: application/json

{
    "projectId":"2",
    "userId":"6"
}


//ASSIGNING PROJECTS TO USERS
###
POST http://localhost:5000/projects/assignProject
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImZpcnN0TmFtZSI6ImRhbiIsImxhc3ROYW1lIjoia2l0aGVrYSIsImVtYWlsIjoia2FraW55aWRrQGdtYWlsLmNvbSIsInJvbGUiOiIxIiwiaWF0IjoxNjYwNTAyOTc0LCJleHAiOjE2NjA1MDMyNzR9.8v1t_Ysl7-0VYii-op04RSULkdGsXvhCG3rKRlxNMzo

{
    "projectId":"6",
    "userId":"2"
}

# CHECKING PENDING PROJECTS
###
POST http://localhost:5000/projects/pendingProjects
Content-Type: application/json


CHECKING COMPLETE PROJECTS
###
POST http://localhost:5000/projects/completeProjects
Content-Type: application/json


//cCHECK IF ASSIGNED PROJECT
###
POST http://localhost:5000/users/assigned
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImZpcnN0TmFtZSI6ImFsZXgiLCJsYXN0TmFtZSI6IndhaWhlbnlhIiwiZW1haWwiOiJseHdhaWhlbnlhQGdtYWlsLmNvbSIsInJvbGUiOiIwIiwiaWF0IjoxNjYwNTEwNjk5LCJleHAiOjE2NjA1MTA5OTl9.wMgODeHNpaNX0IYHmtxQR-pnp-ZaVyJndgh97BtTaus